### ISSUE TITLE
Can we integrate MongoDb ?

### ISSUE THREAD

**Issue by abhishekbhalani** [Domitor/Intwenty#52]
Hi,

Is it possible to use Data Client service for MongoDb collection.

Is it possible to Db connection with MongoDb..

#mongodb

Thank you.

**Comment by jfdomitor** [comment]
Thank you for your interest, untill 1.3.9 there was support for mongodb. But since 1.4.0 the support was dropped.

**Comment by abhishekbhalani** [comment]
> Thank you for your interest, untill 1.3.9 there was support for mongodb. But since 1.4.0 the support was dropped.

@jfdomitor 
May I know reason to dropped support for the Mongo/Nosql database?
Is any issue if use Mongodb/Nosql within application ?

**Comment by jfdomitor** [comment]
Depending on how you use intwenty, a lot of sql is auto generated. It was to much work right now to build a generator for mongo queries that does exactly the same as the generated sql.

Right now its not possible at all to use nosql, sinne intwenty.dataclient does not support it.
